<a href="https://colab.research.google.com/github/vishal-anand-max/DataScienceEssentials/blob/main/MaskingTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ============================
# CELL 1 — MARKDOWN
# ============================

"""
# NumPy Masking — A Complete Hands‑On Notebook

This notebook teaches **masking in NumPy** from first principles.

You will learn:
• Masking based on **values**
• Masking based on **indices**
• Boolean masks vs integer masks
• Why boolean indexing flattens arrays
• When multiplication is better than indexing
• Handy utilities: np.where, np.tri, np.tril, np.triu

Each concept is immediately followed by **practice cells**.
Run everything top‑to‑bottom.
"""


In [ ]:
# ============================
# CELL 2 — CODE
# ============================

import numpy as np
np.set_printoptions(suppress=True)


# ============================
# CELL 3 — MARKDOWN
# ============================

"""
### Masking Based on Values

A **value‑based mask** is created by applying a condition to array values.
The result is a boolean array of the same shape.
"""


In [ ]:
# ============================
# CELL 4 — CODE
# ============================

A = np.array([1.2, 4.0, 7.5, 10.0, 13.0])

mask = A > 5
masked_A = A[mask]

print("A:", A)
print("Mask:", mask)
print("A[mask]:", masked_A)


A: [ 1.2  4.   7.5 10.  13. ]
Mask: [False False  True  True  True]
A[mask]: [ 7.5 10.  13. ]


In [ ]:
# ============================
# CELL 5 — CODE
# ============================

# PRACTICE 1:
# Select only even numbers from 0 to 19

B = np.arange(20)
mask = B % 2 == 0
print(B[mask])


[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# PRACTICE 2:
# Mask out negative values

C = np.array([3.5, -2.1, 0.0, 8.8, -1.0])
mask = C >= 0
print(C[mask])


[3.5 0.  8.8]


# ============================
# CELL 6 — MARKDOWN
# ============================

"""
Boolean indexing **selects elements**, not positions.
The output is always **1‑D**, even if the input is 2‑D.
"""


In [ ]:
# ============================
# CELL 7 — CODE
# ============================

A = np.arange(1, 10).reshape(3, 3)
mask = A % 2 == 0

print("A:\n", A)
print("Mask:\n", mask)
print("A[mask]:", A[mask])


A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mask:
 [[False  True False]
 [ True False  True]
 [False  True False]]
A[mask]: [2 4 6 8]


In [ ]:
# ============================
# CELL 8 — CODE
# ============================

# PRACTICE:
# Predict the shape before running

D = np.arange(16).reshape(4, 4)
mask = D > 5
print(D[mask])


[ 6  7  8  9 10 11 12 13 14 15]


# ============================
# CELL 9 — MARKDOWN
# ============================

"""
If you want to **preserve shape**, use an **integer mask** (0/1)
and apply it via multiplication.
"""


In [ ]:
# ============================
# CELL 10 — CODE
# ============================

A = np.arange(1, 10).reshape(3, 3)
mask_bool = A % 2 == 0
mask_int = mask_bool.astype(int)

print("Integer mask:\n", mask_int)
print("A * mask:\n", A * mask_int)


Integer mask:
 [[0 1 0]
 [1 0 1]
 [0 1 0]]
A * mask:
 [[0 2 0]
 [4 0 6]
 [0 8 0]]


In [ ]:
# ============================
# CELL 11 — CODE
# ============================

# PRACTICE:
# Zero out odd numbers but preserve shape

E = np.arange(1, 17).reshape(4, 4)
mask = (E % 2 == 0).astype(int)
print(E * mask)


[[ 0  2  0  4]
 [ 0  6  0  8]
 [ 0 10  0 12]
 [ 0 14  0 16]]


# ============================
# CELL 12 — MARKDOWN
# ============================

"""
Index‑based masks depend on (i, j), not values.

We generate index grids using np.indices.
"""


In [ ]:
# ============================
# CELL 13 — CODE
# ============================

A = np.arange(1, 10).reshape(3, 3)
I, J = np.indices(A.shape)

mask_lower = I >= J
mask_upper = I < J

print("Lower‑triangular mask:\n", mask_lower.astype(int))
print("Upper‑triangular mask:\n", mask_upper.astype(int))


Lower‑triangular mask:
 [[1 0 0]
 [1 1 0]
 [1 1 1]]
Upper‑triangular mask:
 [[0 1 1]
 [0 0 1]
 [0 0 0]]


In [ ]:
# ============================
# CELL 14 — CODE
# ============================

# PRACTICE 1:
# Mask where i + j is even

mask = (I + J) % 2 == 0
print(mask.astype(int))
# PRACTICE 2:
# Mask only the diagonal

mask = I == J
print(mask.astype(int))


[[1 0 1]
 [0 1 0]
 [1 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


# ============================
# CELL 15 — MARKDOWN
# ============================

"""
NumPy provides direct triangular mask generators.
"""



In [ ]:
# ============================
# CELL 16 — CODE
# ============================

A = np.arange(1, 10).reshape(3, 3)

mask_lower = np.tri(*A.shape, dtype=int)
mask_upper = 1 - mask_lower

print("Lower:\n", A * mask_lower)
print("Upper:\n", A * mask_upper)

Lower:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
Upper:
 [[0 2 3]
 [0 0 6]
 [0 0 0]]


# ============================
# CELL 18 — MARKDOWN
# ============================

"""
np.where(condition, value_if_true, value_if_false)
"""


In [ ]:
# ============================
# CELL 19 — CODE
# ============================

A = np.arange(-5, 5)
result = np.where(A >= 0, A, 0)
print(result)


[0 0 0 0 0 0 1 2 3 4]


In [ ]:
# ============================
# CELL 20 — CODE
# ============================

# PRACTICE:
# Replace odd numbers with -1

B = np.arange(10)
result = np.where(B % 2 == 0, B, -1)
print(result)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# ============================
# CELL 21 — MARKDOWN
# ============================

"""
### Final Challenge

Create a mask that:
• Keeps only the lower triangle
• AND keeps only even values
• Preserves shape
"""


In [ ]:
# ============================
# CELL 22 — CODE
# ============================

A = np.arange(1, 26).reshape(5, 5)
I, J = np.indices(A.shape)

mask = (I >= J) & (A % 2 == 0)
result = A * mask.astype(int)

print(result)


[[ 0  0  0  0  0]
 [ 6  0  0  0  0]
 [ 0 12  0  0  0]
 [16  0 18  0  0]
 [ 0 22  0 24  0]]
